# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts


pool:
  vmImage: 'macOS-10.13'
  
variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore

- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.103'
    
- script: dotnet tool install -g dotnetsay
- script: dotnetsay
 
- script: dotnet test **/dotnetcore-tests/dotnetcore-tests.csproj  --logger trx
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    
    
