# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts


pool:
  vmImage: 'macOS-10.13'
  
variables:
  buildConfiguration: 'Release'


- script: dotnet restore

- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.103'
    

    
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1
